### ISSUE TITLE
Rmagic not available for this version of R

### ISSUE THREAD

**Issue by BaptisteSadoughi** [cran/Rmagic#2]
Hello,
I am trying to install Rmagic for PHATE but encounter the error
> install.packages("Rmagic")
Warning in install.packages :
  package ‘Rmagic’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

R version 4.2.2 and 4.3 but I could not find the version requirement for Rmagic from the doc. Could you help with this?

Many thanks in advance for your time,
Best,

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by BaptisteSadoughi** [comment]
Hi, I just saw the older closed comment on a similar issue and the solution you provided back then seems to have solved it. Thanks!
